package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Nacho
 */
public class Mutacion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Mutacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelIndex1 = new javax.swing.JLabel();
        jLabelIndex2 = new javax.swing.JLabel();
        jLabelExito = new javax.swing.JLabel();
        jLabelPorcent = new javax.swing.JLabel();
        jTextFieldIndex1 = new javax.swing.JTextField();
        jTextFieldIndex2 = new javax.swing.JTextField();
        jTextFieldExito = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabelTitulo.setForeground(java.awt.Color.darkGray);
        jLabelTitulo.setText("<html> <center>Algoritmo de Mutación</center> <br> <center>Método: 2-Opt</center> <br> </html>");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 390, 120));

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDescripcion.setText("<html>\nDescripción\n<br>\n<em>Mutación de un segmento (invertir orden) según parámetros que<br> indiquen\nel tamaño del segmento dado un índice inicial y final. Además se incluye la opción\nde ajustar la probabilidad de mutación.\n.</em>\n<br>\n</html>");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 400, 100));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabelIndex1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIndex1.setText("Índice de inicio del segmento");
        getContentPane().add(jLabelIndex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 160, 20));

        jLabelIndex2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIndex2.setText("Índice de final del segmento");
        getContentPane().add(jLabelIndex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 160, 20));

        jLabelExito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelExito.setText("Probabilidad de mutar");
        getContentPane().add(jLabelExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 160, 20));

        jLabelPorcent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPorcent.setText("%");
        getContentPane().add(jLabelPorcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 20, 20));

        jTextFieldIndex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIndex1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIndex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 50, -1));
        getContentPane().add(jTextFieldIndex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 50, -1));

        jTextFieldExito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExitoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 50, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 102));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 110, 40));

        jButtonAceptar.setBackground(new java.awt.Color(0, 0, 102));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 110, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        int index1 = Integer.parseInt(jTextFieldIndex1.getText());
        int index2 = Integer.parseInt(jTextFieldIndex2.getText());
        double exito = Integer.parseInt(jTextFieldExito.getText());
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldIndex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIndex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIndex1ActionPerformed

    private void jTextFieldExitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mutacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelExito;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIndex1;
    private javax.swing.JLabel jLabelIndex2;
    private javax.swing.JLabel jLabelPorcent;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldExito;
    private javax.swing.JTextField jTextFieldIndex1;
    private javax.swing.JTextField jTextFieldIndex2;
    // End of variables declaration//GEN-END:variables

    
}
