package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Nacho
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOpcion2 = new javax.swing.JButton();
        jButtonOpcion1 = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelIntro = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOpcion2.setBackground(new java.awt.Color(70, 0, 0));
        jButtonOpcion2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOpcion2.setText("<html>\n<center>¡No hay tiempo!</center>\n<br>\n<center>Vamos a lo importante</center>\n\n</html>");
        jButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 270, 80));

        jButtonOpcion1.setBackground(new java.awt.Color(0, 55, 0));
        jButtonOpcion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOpcion1.setText("<html>\n<center>Recorrido guiado a través</center>\n<br>\n<center>del algoritmo genético</center>\n\n</html>");
        jButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 270, 80));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabelIntro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelIntro.setForeground(java.awt.Color.darkGray);
        jLabelIntro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIntro.setText("<html>\n<center>Seleccione una opción</center>\n</html>");
        jLabelIntro.setToolTipText("");
        jLabelIntro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 380, 110));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion1ActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOpcion1ActionPerformed

    private void jButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion2ActionPerformed
        Parametros parametros = new Parametros();
        parametros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOpcion2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpcion1;
    private javax.swing.JButton jButtonOpcion2;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIntro;
    // End of variables declaration//GEN-END:variables
}
