package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import tarea3.Metodos;
import static tarea3.Metodos.*;
/**
 *
 * @author Nacho
 */
public class Principal extends javax.swing.JFrame {
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Texto","txt");
    
    public static File original;

    /**
     * Creates new form Inicio
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCruzamiento = new javax.swing.JButton();
        jButtonMutacion = new javax.swing.JButton();
        jButtonSeleccion = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jLabelValidar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCruzamiento.setBackground(new java.awt.Color(0, 0, 102));
        jButtonCruzamiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCruzamiento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCruzamiento.setText("Cruzamiento");
        jButtonCruzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCruzamientoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCruzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, 60));

        jButtonMutacion.setBackground(new java.awt.Color(0, 0, 102));
        jButtonMutacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMutacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMutacion.setText("Mutación");
        jButtonMutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMutacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 180, 60));

        jButtonSeleccion.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSeleccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeleccion.setText("Selección de padres");
        jButtonSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 180, 60));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jButtonAbrir.setText("Abir archivo...");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabelValidar.setText("No se ha seleccionado archivo");
        getContentPane().add(jLabelValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 280, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Sale del programa
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        //Creación un objeto JFileChooser
        JFileChooser dlg = new JFileChooser();
        //Se llamará al método del objeto creado
        dlg.setFileFilter(filter);
        //Se abre la ventana de diálogo para seleccionar archivo
        int option = dlg.showOpenDialog(this);
        //Si hacemos click en el botón abir
        if (option==JFileChooser.APPROVE_OPTION)
        {
            //Se obtiene el nombre del archivo seleccionado
            String rutaCompleta = dlg.getSelectedFile().getPath();
            //Crear variable a partir de la selección
            original = new File(rutaCompleta);
            //Traspasar nombre de archivo a label adyacente
            String label = "Archivo seleccionado exitosamente: "+original.getName();
            jLabelValidar.setText(label);
            //jLabelValidar.setForeground(Color.green);
            Metodos.ruta = rutaCompleta;
            //Generar archivo temporal dentro del directorio raiz
            crearArchivo();
            //Crear matriz 2D con los costos de distancias entre las ciudades
            crearMatriz();
        }
        else
        {
            //Transmitir error en caso que se cancele la carga del archivo
            String label = "Carga de archivo fallida, intente nuevamente.";
            jLabelValidar.setText(label);
            //jLabelValidar.setForeground(Color.red);//
        }
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionActionPerformed
        Seleccion seleccion = new Seleccion();
        seleccion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSeleccionActionPerformed

    private void jButtonCruzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCruzamientoActionPerformed
        int[][] matrix = new int[15][29];
        int[] mostrar = new int[29];
        for(int i=0;i<15;i++)
        {
            for(int j=0;j<29;j++)
            {
                matrix[i][j] = i;
            }
        }
        mostrar = extraerArray(3,matrix);
        imprimirArreglo(mostrar);
    }//GEN-LAST:event_jButtonCruzamientoActionPerformed

    private void jButtonMutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMutacionActionPerformed
        int[] prueba = {1,44,5,3,73,-1,0,-53};
        System.out.println(obtenerMin(prueba));
        System.out.println(obtenerMax(prueba)); 
        /*int[] asdf = randomArray(6,5);
        int[][] matriz = {{0,0,0},{1,1,1},{2,2,2},{3,3,3}};
        int[] array = extraerArray(1,matriz);
        imprimirArreglo(array);
        array = extraerArray(3,matriz);
        imprimirArreglo(array);
        array = extraerArray(2,matriz);
        imprimirArreglo(array);
        array = extraerArray(5,matriz);
        imprimirArreglo(array);*/
        
        
        System.out.println("FUNCIONÓ !!!!");
    }//GEN-LAST:event_jButtonMutacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonCruzamiento;
    private javax.swing.JButton jButtonMutacion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeleccion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelValidar;
    // End of variables declaration//GEN-END:variables
}
